### ISSUE TITLE
Where was the passport.js used?

### ISSUE THREAD

**Issue by ssdwho** [rpichioli/react-with-nodejs-and-sequelize#29]
I couldn't see the passport.js usage. The project is not over yet?

**Comment by rpichioli** [comment]
Hi @ssdwho.

The passport implementation was in my plan but it is dropped.

At first I was thinking about implement passport but I'm thinking now in keep it covering basic techniques and concepts of REST API with NodeJS + Express building CRUDs and consume it with React + Redux SPA.

I'm creating some security focused apps and passport is part of it, I'll build a new repo in the future.

Let me know if you have some tips or ideas.
